# Combine workflow for pull-request, push-to-main and release events.

name: EE Build

on:
  pull_request_target:
    branches:
      - main
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  ee-build:
    uses: ansible/ansible-content-actions/.github/workflows/ee-build.yml@main
