name: EE Build

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

  build-ee:
    needs: [prepare]
    runs-on: ubuntu-latest
    environment: ${{ github.event_name }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Fetch the base and head refs
        run: |
          git fetch origin ${{ github.base_ref }}
          git fetch origin ${{ github.head_ref }}

      - name: Install python requirements
        run: |
          pip install ansible-builder
          pip install ansible-navigator

      - name: Define environment variables
        run: |
          echo "EE=`yq -r '.options.tags[0]' 'execution-environment.yml'`" >> $GITHUB_ENV
          echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          echo "EE_file=execution-environment.yml" >> $GITHUB_ENV

      - name: Login to ghcr
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: (devel) Build image and create artifact
        run: |
          echo "Would build: ${{ env.EE }}"

      - name: Build image and create artifact
        run: |
          ansible-builder build -v 3 \
          --build-arg AH_TOKEN=${{ secrets.AH_TOKEN }} \
          --context=../${{ env.EE }} \
          --tag=${{ env.EE }}:${{ env.IMAGE_TAG }} \
          --tag=${{ env.EE }}:${{ github.sha }}

          # Create artifact file
          COMMANDS_FILE="commands-${{ env.EE }}.txt"
          echo "" >> $COMMANDS_FILE
          echo "EE: ${{ env.EE }}" >> $COMMANDS_FILE
          echo "" >> $COMMANDS_FILE
          echo "\`\`\`" > $COMMANDS_FILE
          echo "podman pull ghcr.io/${{ github.repository_owner }}/${{ env.EE }}:${{ env.IMAGE_TAG }}" >> $COMMANDS_FILE
          echo "\`\`\`" >> $COMMANDS_FILE
          echo "<details>" >> $COMMANDS_FILE
          echo "<summary><b>More info...</b></summary>" >> $COMMANDS_FILE
          echo "" >> $COMMANDS_FILE
          echo "#### Installed collections" >> $COMMANDS_FILE
          echo "" >> $COMMANDS_FILE
          echo "\`\`\`" >> $COMMANDS_FILE
          podman run -it ${{ env.EE }}:${{ env.IMAGE_TAG }} ansible-galaxy collection list  >> $COMMANDS_FILE
          echo "\`\`\`" >> $COMMANDS_FILE
          echo "" >> $COMMANDS_FILE
          echo "#### EE Testing" >> $COMMANDS_FILE
          echo "" >> $COMMANDS_FILE
          echo "\`\`\`" >> $COMMANDS_FILE
          podman run -it ${{ env.EE }}:${{ env.IMAGE_TAG }} ansible-navigator --version  >> $COMMANDS_FILE
          echo "\`\`\`" >> $COMMANDS_FILE
          echo "" >> $COMMANDS_FILE
          echo "#### Ansible version" >> $COMMANDS_FILE
          echo "" >> $COMMANDS_FILE
          echo "\`\`\`" >> $COMMANDS_FILE
          podman run -it ${{ env.EE }}:${{ env.IMAGE_TAG }} ansible --version  >> $COMMANDS_FILE
          echo "\`\`\`" >> $COMMANDS_FILE
          echo "</details>" >> $COMMANDS_FILE

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: commands-${{ env.EE }}
          path: ./commands-${{ env.EE }}.txt

      - name: Push To GHCR
        id: push_to_ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.EE }}
          tags: ${{ env.IMAGE_TAG }} ${{ github.sha }}
          registry: ghcr.io/${{ github.repository_owner }}

      - name: Print summary
        run: |
          echo "## Usage" >> $GITHUB_STEP_SUMMARY
          echo "Image pushed to repository: ghcr.io/${{ github.repository_owner }}/${{ env.EE }}:${{ env.IMAGE_TAG }}" >> $GITHUB_STEP_SUMMARY
          echo "> \`podman pull ghcr.io/${{ github.repository_owner }}/${{ env.EE }}:${{ env.IMAGE_TAG }}\`" >> $GITHUB_STEP_SUMMARY
